### ISSUE TITLE
Does this still work? 

### ISSUE THREAD

**Issue by s-murphy1** [ChristopherRogers1991/mycroft_routine_skill#13]
I have installed this skill several different ways. Does it still work? I am tryin to debug it and it would be nice if someone could tell me if the file structure is still supported

**Comment by ChristopherRogers1991** [comment]
It should still work. Can you describe the specific issue you are having?

Note that you may have a 'routines.json' and 'routines2.json' file. Be sure to use 2 if it is present. The layout is slightly different - the skill should automatically convert routines.json to routines2.json if it is present, on the first run of a version of the skill that supports the new format.

**Comment by s-murphy1** [comment]
I tried both manual and msm installation. "create routine" is replied to with "I don't know what that means"

**Comment by ChristopherRogers1991** [comment]
Can you check the Mycroft skills log, and look for errors loading the skill?

The log should be at /var/log/mycroft/skills.log.

**Comment by s-murphy1** [comment]
Fixed it, turned out to be a path installation issue
Here is the solution:
https://github.com/MycroftAI/documentation/blob/master/docs/skill-development/mycroft-skills-manager/msm-troubleshooting.md#updating-the-path-variable
