### ISSUE TITLE
Errors when I try to run skill

### ISSUE THREAD

**Issue by im-strongthany-zz** [ChristopherRogers1991/mycroft_routine_skill#2]
Saying "Good Morning" results in the following in the debug log. 
Running Mycroft 18.2.9 on Ubuntu 18.04

`10:36:27.379 - __main__:handle_utterance:61 - INFO - Utterance: ['good morning']`

`10:36:27.399 - mycroft.skills.core:wrapper:607 - ERROR - An error occurred while processing a`
`request in Mycroft Routine Skill`

`Traceback (most recent call last):`

`File "/home/parker/mycroft-core/mycroft/skills/core.py", line 598, in wrapper`
`handler(message)`

`File "/opt/mycroft/skills/routine.christopherrogers1991/__init__.py", line 143, in _trigger_routine`
`self._run_routine(name)`

`File "/opt/mycroft/skills/routine.christopherrogers1991/__init__.py", line 146, in _run_routine`
`for task in self._routines[name]['tasks']:`

`KeyError: 'tasks'`

**Comment by ChristopherRogers1991** [comment]
Hey @pseams,

Thanks for filling this.

In `~mycroft/.mycroft/skills/MycroftRoutineSkill`, there should be a file called `routines.json`. Can you send the contents of that file?

Note that the path above assumes you're using a Mark1. If you're using this on your desktop, the path should be: `~/.mycroft/skills/MycroftRoutineSkill/routines.json`

Also, have you tried creating/running any other routines? If so, do they work?

Thanks,

-Chris

**Comment by ChristopherRogers1991** [comment]
@pseams, just want to check in - is this still an issue? If so, can you send me the contents of the routines.json file I mentioned in my previous comment?

-Chris

**Comment by ChristopherRogers1991** [comment]
I'm going to go ahead and close this out, since I haven't heard back. Feel free to message me here if you'd like to re-open and continue troubleshooting.
