### ISSUE TITLE
Add routines into OpenVoiceOS

### ISSUE THREAD

**Issue by AIIX** [ChristopherRogers1991/mycroft_routine_skill#20]
Hey ! there seems to be some awesome stuff happening here..

Would you be interested to incorporate this routines system into OpenVoiceOS ? (https://github.com/OpenVoiceOS / https://openvoiceos.com / https://community.mycroft.ai/t/openvoiceos-a-bare-minimal-production-type-of-os-based-on-buildroot/)

As a skill this should already work as we are backwards compatible with mycroft-core dev branch but we would like to deeper integrate routines into the ovos ecosystem.

These are just some initial deeper integration ideas I have for routines:
- Skill provides voice interface
- Move all internal routine management logic from the skill interface to a PHAL Plugin: (what are PHAL plugins? https://github.com/OpenVoiceOS/community-docs#what-is-phal), PHAL plugins in ovos world are also platform integrations and allow for more abstract services that act as intercommunication API's for internals ("this is where i see routines logic living as a service")
- Moving the routines logic to a PHAL plugin and making it an always available service also lets us incorporate this with external applications like KDE Connect so routines can be controlled even from an android phone
- Add routines as a tabbed interface on our homescreen quick access dashboard
  - Listing added routine cards
  - Adding a new routine
  - Delete / Modify existing routine

- It also seems you do have a GUI interface also for the routines skill already :smile: makes it already much easier to integrate with 

What our homescreen dashboard looks like: 
![dash-quick(2)](https://user-images.githubusercontent.com/19663666/195478262-530809f9-b43b-4614-bae9-101bd65018f0.gif)

If this sounds like an interesting idea to you and everyone working on this or if you got any feedback on this or some cooler integration ideas, do join us on our matrix dev chat channel to discuss and participate :)

**Comment by ChristopherRogers1991** [comment]
Closing this out - @AIIX , and I chatted, and determined the OVOS project has a hard stance about not using GPL code. This project is GPLv3, and thus incompatible with their goals.
